### ISSUE TITLE
Error while hosting on paw

### ISSUE THREAD

**Issue by nkming2** [nkming2/google-search-telegram-bot#1]
As reported by @abusahl

**Comment by nkming2** [comment]
@abusahl Please post the error message or log related to this issue. My instance is still running normally on PAW at the moment

**Comment by abusahl** [comment]
I'm new to python.. and I was unable to deploy it on pythonanywhere using clone nor upload.. I have read "how to's" in readme files. I have try many times even in virtualenv..

**Comment by nkming2** [comment]
But what do you mean by "unable"? What happens after you running `pip install -e .` following the instructions? Or does it fail during runtime?

**Comment by abusahl** [comment]
failed to run setup

`/setWebhook (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f760c8699e8>: Failed to es
tablish a new connection: [Errno 101] Network is unreachable',))`

I have edit config.json and set webhook

**Comment by abusahl** [comment]
Have you try to run on python 3.6 ? As default on pythonanywhere?

**Comment by abusahl** [comment]
/src/app/config_loader.py", line 9, in load
    return ConfigLoader._ensure_config()[identifier]
KeyError: 'xxxxxxxx:AAFxxxxxxxxxEJQm6oxaymz-DWTxxxxxxxx'

**Comment by nkming2** [comment]
> Have you try to run on python 3.6 ? As default on pythonanywhere?
No. I'm currently running on 3.5 but I believe they should work similarly

**Comment by abusahl** [comment]
Hello this is my config.json:
`{
	"telegram_bot_token": "mybottoken",
	"google_api_key": "mycseapikey",
	"search_engine_id": "partner-pub-mysearchengineID",
	"allow_only_users": [],
	"paw_app": {
		"url": "https://mypythonanywhereusername.pythonanywhere.com",
		"webhook_secret": "XXXXXXXXXXXX"
	}
}
`

**Comment by abusahl** [comment]
Here is my web app log:

`2018-05-04 01:01:17,493: ***************************************************
2018-05-04 01:01:17,493: If you're seeing an import error and don't know why,
2018-05-04 01:01:17,493: we have a dedicated help page to help you debug: 
2018-05-04 01:01:17,493: https://help.pythonanywhere.com/pages/DebuggingImportError/
2018-05-04 01:01:17,493: ***************************************************
2018-05-04 12:05:12,049: Error running WSGI application
2018-05-04 12:05:12,303: ImportError: No module named 'telepot'
2018-05-04 12:05:12,303:   File "/var/www/mysite_pythonanywhere_com_wsgi.py", line 16, in <module>
2018-05-04 12:05:12,303:     from app.paw_app import flask_app as application  # noqa
2018-05-04 12:05:12,303: 
2018-05-04 12:05:12,304:   File "/home/mysite/google-search-telegram-bot/src/app/__init__.py", line 3, in <module>
2018-05-04 12:05:12,304:     from app.standalone_app import StandaloneApp
2018-05-04 12:05:12,304: 
2018-05-04 12:05:12,304:   File "/home/mysite/google-search-telegram-bot/src/app/standalone_app.py", line 1, in <module>
2018-05-04 12:05:12,304:     import telepot
2018-05-04 12:05:12,306: ***************************************************
2018-05-04 12:05:12,306: If you're seeing an import error and don't know why,
2018-05-04 12:05:12,306: we have a dedicated help page to help you debug: 
2018-05-04 12:05:12,307: https://help.pythonanywhere.com/pages/DebuggingImportError/
2018-05-04 12:05:12,307: ***************************************************`

**Comment by nkming2** [comment]
Can you paste the output after running `pip install -e .` in `/home/mysite/google-search-telegram-bot`?

**Comment by abusahl** [comment]
here it is

`Running setup.py develop for google-search-telegram-bot
    Complete output from command /usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/rujukan/google-search-telegram-bot/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-12050.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/local/lib/python2.7/dist-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.readthedocs.io/en/latest/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    
    ----------------------------------------
Command "/usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/mysite/google-search-telegram-bot/setup.py';exec(compile(getattr(
tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/mysite/goo
gle-search-telegram-bot/`

**Comment by nkming2** [comment]
python2.7? That's very weird... Let's try `pip3 install -e --user .`

**Comment by abusahl** [comment]
I have tried this one too..

"python2.7? That's very weird... Let's try pip3 install --user -e ."

**Comment by nkming2** [comment]
> I have tried this one too..

Can you also paste the output? thanks!

**Comment by abusahl** [comment]
My web app also shows error when I try to open:

Mysite.pythonanywhere.com

.... Unhandled exception

**Comment by abusahl** [comment]
Yes I replace them, but now I have revert to its original :)

Now happen this:

` raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/setWebhook (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f74addceb70>: Failed to es
tablish a new connection: [Errno 101] Network is unreachable',))`

**Comment by nkming2** [comment]
We are having progress :smiley:
Are you running the PAW specific entry point from the WSGI file? Make sure it looks mostly the same as https://github.com/nkming2/google-search-telegram-bot/blob/master/misc/pythonanywhere_com_wsgi.py
In particular, these few lines:
```
from app.paw_app import PawApp
PawApp().run()
# import flask app but need to call it "application" for WSGI to work
from app.paw_app import flask_app as application
```

**Comment by abusahl** [comment]
Still the same errno 101

**Comment by nkming2** [comment]
If you really want to run it from the console, you need to copy the _init_paw_telepot() function from paw_app.py and run it in standalone_app.py (preferably in __init__)

**Comment by abusahl** [comment]
Hello, can i give you access to my site in pythonanywhere ? Please give me your telegram username.. thank you..

**Comment by abusahl** [comment]
This Problem is fixed when I run all from the start in /var/www/

_Think to avoid google cse 100 query per day limitation_

**Comment by nkming2** [comment]
Great, I'll now close the issue :) 

> I thinking about to avoid google cse 100 query per day limitation

Technically you could get rid of it with a pool of Google accounts. BUT, this will very likely violate their terms
